env:
  - ABV=2.4.22

before_install:
  - ls
  - pwd


install:
  - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh --quiet
  - rcSetup Base,${ABV}
  - git clone https://github.com/UCATLAS/xAODAnaHelpers
  - cd xAODAnaHelpers && git checkout 3d2a40eca4f2d110 && cd ../
  - python xAODAnaHelpers/scripts/checkoutASGtags.py ${ABV}
  - python MultijetBalance/scripts/checkoutASGtags.py ${ABV}
  - rc clean
  - rc find_packages

script:
  - rc compile

